USE [master]
GO

/****** Object:  Database [MTBMS] ******/
CREATE DATABASE [MTBMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MTBMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MTBMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MTBMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MTBMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [MTBMS] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MTBMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MTBMS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MTBMS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MTBMS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MTBMS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MTBMS] SET ARITHABORT OFF 
GO
ALTER DATABASE [MTBMS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MTBMS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MTBMS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MTBMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MTBMS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MTBMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MTBMS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MTBMS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MTBMS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MTBMS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MTBMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MTBMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MTBMS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MTBMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MTBMS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MTBMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MTBMS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MTBMS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MTBMS] SET  MULTI_USER 
GO
ALTER DATABASE [MTBMS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MTBMS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MTBMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MTBMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MTBMS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MTBMS] SET QUERY_STORE = OFF
GO
USE [MTBMS]
GO
/****** Object:  Table [dbo].[Users]  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO 
CREATE TABLE [dbo].[Users](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](50) NULL,
	[Password] [varchar](550) NULL,
	[AccessID] [int] NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Access]  ******/
CREATE TABLE [dbo].[Access](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
 CONSTRAINT [PK_Access] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


INSERT [dbo].[Users] ([Username], [Password], [AccessID]) VALUES (N'admin', N'123456', 1)
INSERT [dbo].[Users] ([Username], [Password], [AccessID]) VALUES (N'user', N'user', 2)
INSERT [dbo].[Access] ([Name]) VALUES (N'Admini')
INSERT [dbo].[Access] ([Name]) VALUES (N'Useri')


ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_Access] FOREIGN KEY([AccessID])
REFERENCES [dbo].[Access] ([ID])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_Access]
GO


/****** Object:  Table [dbo].[Cinema]  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cinema](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](150) NULL,
	[City] [varchar] (150) NULL,
 CONSTRAINT [PK_Cinema] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Movie]  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movie](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MovieName] [varchar](50) NULL,
	[Date] [date] NULL,
	[CinemaID] [int] NULL,
 CONSTRAINT [PK_Movie] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Ticket]  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ticket](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TicketName] [varchar](50) NULL,
	[CinemaID] [int] NULL,
	[MovieID] [int] NULL,
 CONSTRAINT [PK_Ticket] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[ComingSoon]  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ComingSoon](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CSMovieName] [varchar](50) NULL,
	[Date] [date] NULL,
	[CinemaID] [int] NULL,
 CONSTRAINT [PK_ComingSoon] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[BookedTicket]  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookedTicket](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BookedName] [varchar](50) NULL,
	[TicketID] [int] NULL,
 CONSTRAINT [PK_BookedTicket] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Movie]  WITH CHECK ADD  CONSTRAINT [FK_Movie_Cinema] FOREIGN KEY([CinemaID])
REFERENCES [dbo].[Cinema] ([ID])
GO
ALTER TABLE [dbo].[Movie] CHECK CONSTRAINT [FK_Movie_Cinema]
GO
USE [master]
GO
ALTER DATABASE [MTBMS] SET  READ_WRITE 
GO

ALTER TABLE [dbo].[Ticket]  WITH CHECK ADD  CONSTRAINT [FK_Ticket_Cinema] FOREIGN KEY([CinemaID])
REFERENCES [dbo].[Cinema] ([ID])
GO
ALTER TABLE [dbo].[Ticket] CHECK CONSTRAINT [FK_Ticket_Cinema]
GO
USE [master]
GO
ALTER DATABASE [MTBMS] SET  READ_WRITE 
GO

ALTER TABLE [dbo].[Ticket]  WITH CHECK ADD  CONSTRAINT [FK_Ticket_Movie] FOREIGN KEY([MovieID])
REFERENCES [dbo].[Movie] ([ID])
GO
ALTER TABLE [dbo].[Ticket] CHECK CONSTRAINT [FK_Ticket_Movie]
GO
USE [master]
GO
ALTER DATABASE [MTBMS] SET  READ_WRITE 
GO

ALTER TABLE [dbo].[ComingSoon]  WITH CHECK ADD  CONSTRAINT [FK_ComingSoon_Cinema] FOREIGN KEY([CinemaID])
REFERENCES [dbo].[Cinema] ([ID])
GO
ALTER TABLE [dbo].[ComingSoon] CHECK CONSTRAINT [FK_ComingSoon_Cinema]
GO
USE [master]
GO
ALTER DATABASE [MTBMS] SET  READ_WRITE 
GO

ALTER TABLE [dbo].[BookedTicket]  WITH CHECK ADD  CONSTRAINT [FK_BookedTicket_Ticket] FOREIGN KEY([TicketID])
REFERENCES [dbo].[Ticket] ([ID])
GO
ALTER TABLE [dbo].[BookedTicket] CHECK CONSTRAINT [FK_BookedTicket_Ticket]
GO
USE [master]
GO
ALTER DATABASE [MTBMS] SET  READ_WRITE 
GO
