/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import javax.swing.JOptionPane;

/**
 *
 * @author Spectre
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param userAccess
     */
    public AdminHome(int userAccess){
        initComponents();
        setLocationRelativeTo(null);
        if(userAccess!=1){
            comingsoonBtn.setVisible(false);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinemasBtn = new javax.swing.JButton();
        moviesBtn = new javax.swing.JButton();
        comingsoonBtn = new javax.swing.JButton();
        ticketsBtn = new javax.swing.JButton();
        adminpanelLabel = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 724));
        setMinimumSize(new java.awt.Dimension(1280, 724));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 724));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cinemasBtn.setBackground(new java.awt.Color(0, 153, 153));
        cinemasBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cinemasBtn.setForeground(new java.awt.Color(0, 51, 51));
        cinemasBtn.setText("Cinemas");
        cinemasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinemasBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cinemasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, 39));

        moviesBtn.setBackground(new java.awt.Color(0, 153, 153));
        moviesBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        moviesBtn.setForeground(new java.awt.Color(0, 51, 51));
        moviesBtn.setText("Movies");
        moviesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(moviesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 39));

        comingsoonBtn.setBackground(new java.awt.Color(0, 153, 153));
        comingsoonBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comingsoonBtn.setForeground(new java.awt.Color(0, 51, 51));
        comingsoonBtn.setText("Coming Soon");
        comingsoonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comingsoonBtnActionPerformed(evt);
            }
        });
        getContentPane().add(comingsoonBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 171, 39));

        ticketsBtn.setBackground(new java.awt.Color(0, 153, 153));
        ticketsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ticketsBtn.setForeground(new java.awt.Color(0, 51, 51));
        ticketsBtn.setText("Tickets");
        ticketsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ticketsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, 39));

        adminpanelLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        adminpanelLabel.setForeground(new java.awt.Color(0, 153, 153));
        adminpanelLabel.setText("Admin Panel");
        getContentPane().add(adminpanelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 31, 31));

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1249, 689, 31, 31));

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg1.jpg"))); // NOI18N
        getContentPane().add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cinemasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinemasBtnActionPerformed
        // TODO add your handling code here:
        new CinemaForm().setVisible(true);
    }//GEN-LAST:event_cinemasBtnActionPerformed

    private void moviesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviesBtnActionPerformed
        // TODO add your handling code here:
        new MovieForm().setVisible(true);
    }//GEN-LAST:event_moviesBtnActionPerformed

    private void comingsoonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comingsoonBtnActionPerformed
        // TODO add your handling code here:
        new ComingSoonForm().setVisible(true);
    }//GEN-LAST:event_comingsoonBtnActionPerformed

    private void ticketsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketsBtnActionPerformed
        // TODO add your handling code here:
        new TicketForm().setVisible(true);
    }//GEN-LAST:event_ticketsBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you want to close the application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to logout?", "Select", JOptionPane.YES_NO_OPTION);
        if(a == 0) {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminHome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminpanelLabel;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JButton cinemasBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton comingsoonBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton moviesBtn;
    private javax.swing.JButton ticketsBtn;
    // End of variables declaration//GEN-END:variables
}
