/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.Cinema;
import BLL.ComingSoon;
import DAL.CinemaRepository;
import DAL.ComingSoonRepository;
import DAL.CrudFormException;
import GUI.Model.CinemaComboBoxModel;
import GUI.Model.ComingSoonTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Spectre
 */
public class ComingSoonForm extends javax.swing.JFrame {

    ComingSoonRepository csr = new ComingSoonRepository();
    CinemaRepository cr = new CinemaRepository();
    ComingSoonTableModel cstm = new ComingSoonTableModel();
    CinemaComboBoxModel ccbm = new CinemaComboBoxModel();
    
    
    /**
     * Creates new form ComingSoonForm
     */
    public ComingSoonForm() {
        initComponents();
        loadTable();
        tabelaSelectedIndexChange();
        loadComboBox();
    }
    
    public void loadTable(){
        try{
            List<ComingSoon> list = csr.findAll();
            cstm.addList(list);
            table.setModel(cstm);
            cstm.fireTableDataChanged();
        }catch(CrudFormException ex){
            Logger.getLogger(CinemaForm.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    private void tabelaSelectedIndexChange(){
        final ListSelectionModel rowSM = table.getSelectionModel();
        rowSM.addListSelectionListener((ListSelectionEvent e) -> {
            if(e.getValueIsAdjusting()){
                return;
            }
            ListSelectionModel rowSM1 = (ListSelectionModel) e.getSource();
            int selectedIndex = rowSM1.getAnchorSelectionIndex();
            if(selectedIndex > -1){
                ComingSoon cs = cstm.getComingSoon(selectedIndex);
                idField.setText(cs.getId().toString());
                movienameField.setText(cs.getCSMovieName());
                dateField.setDate(cs.getDate());
                ccbm.setSelectedItem(cs.getCinemaID());
                cinemaComboBox.repaint();
            }
        });
    }
    
    public void loadComboBox(){
        try{
            List<Cinema> lista = cr.findAll();
            ccbm.add(lista);
            cinemaComboBox.setModel(ccbm);
            cinemaComboBox.repaint();
        }catch(CrudFormException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        movienameLabel = new javax.swing.JLabel();
        movienameField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        cinemaLabel = new javax.swing.JLabel();
        cinemaComboBox = new javax.swing.JComboBox();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        dateField = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(195, 100));
        setMinimumSize(new java.awt.Dimension(1050, 650));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idLabel.setBackground(new java.awt.Color(0, 153, 153));
        idLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 51, 51));
        idLabel.setText("ID:");
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 61, -1, -1));

        idField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idField.setEnabled(false);
        getContentPane().add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 58, 49, -1));

        movienameLabel.setBackground(new java.awt.Color(0, 153, 153));
        movienameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movienameLabel.setForeground(new java.awt.Color(0, 51, 51));
        movienameLabel.setText("Movie Name ");
        getContentPane().add(movienameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 61, -1, -1));

        movienameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(movienameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 58, 245, -1));

        dateLabel.setBackground(new java.awt.Color(0, 153, 153));
        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(0, 51, 51));
        dateLabel.setText("Date");
        getContentPane().add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 61, 61, -1));

        cinemaLabel.setBackground(new java.awt.Color(0, 153, 153));
        cinemaLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cinemaLabel.setForeground(new java.awt.Color(0, 51, 51));
        cinemaLabel.setText("Cinema");
        getContentPane().add(cinemaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 61, -1, -1));

        cinemaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cinemaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 60, 110, -1));

        saveButton.setBackground(new java.awt.Color(0, 153, 153));
        saveButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 51, 51));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 399, -1, -1));

        cancelButton.setBackground(new java.awt.Color(0, 153, 153));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(0, 51, 51));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 399, -1, -1));

        deleteButton.setBackground(new java.awt.Color(0, 153, 153));
        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(0, 51, 51));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 399, -1, -1));
        getContentPane().add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 60, 140, -1));

        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Movie Name", "Date", "Cinema"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1030, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try{
            int row = table.getSelectedRow();
            if(row == -1){
                ComingSoon cs = new ComingSoon();
                cs.setCSMovieName(movienameField.getText());
                cs.setDate(dateField.getDate());
                cs.setCinemaID((Cinema)ccbm.getSelectedItem());
                csr.create(cs);
            }else{
                ComingSoon cs = cstm.getComingSoon(row);
                cs.setCSMovieName(movienameField.getText());
                cs.setDate(dateField.getDate());
                cs.setCinemaID((Cinema)ccbm.getSelectedItem());
                csr.edit(cs);
            }
            clear();
            loadTable();
        }catch(CrudFormException ex){
            JOptionPane.showMessageDialog(this, "This movie is already registered!");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row != -1){
            Object[] ob = {"Yes","No"};
            int i = JOptionPane.showOptionDialog(this,"Are you sure you want to delete thisi?","Delete", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
            if(i == 0){
                ComingSoon cs = cstm.getComingSoon(row);
                try{
                    csr.delete(cs);
                }catch(CrudFormException ex){
                    JOptionPane.showMessageDialog(this,ex.getMessage());
                }
                clear();
                loadTable();
            }else{
                clear();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Please select something to be deleted?");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed
    
    public void clear(){
        table.clearSelection();
        idField.setText("");
        movienameField.setText("");
        cinemaComboBox.setSelectedIndex(-1);
        cinemaComboBox.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComingSoonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComingSoonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComingSoonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComingSoonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ComingSoonForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox cinemaComboBox;
    private javax.swing.JLabel cinemaLabel;
    private com.toedter.calendar.JDateChooser dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField movienameField;
    private javax.swing.JLabel movienameLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
